import 'package:flutter/material.dart';

final ColorScheme lightMonochrome = ColorScheme(
  brightness: Brightness.light,
  primary: Colors.black,
  onPrimary: Colors.white,
  primaryContainer: Colors.grey.shade300,
  onPrimaryContainer: Colors.black,
  secondary: Colors.black87,
  onSecondary: Colors.white,
  secondaryContainer: Colors.grey.shade200,
  onSecondaryContainer: Colors.black,
  tertiary: Colors.black54,
  onTertiary: Colors.white,
  tertiaryContainer: Colors.grey.shade100,
  onTertiaryContainer: Colors.black,
  error: Colors.black,
  onError: Colors.white,
  errorContainer: Colors.grey.shade300,
  onErrorContainer: Colors.black,
  background: Colors.white,
  onBackground: Colors.black,
  surface: Colors.white,
  onSurface: Colors.black,
  surfaceVariant: Colors.grey.shade100,
  onSurfaceVariant: Colors.black87,
  outline: Colors.grey.shade400,
  shadow: Colors.black,
  inverseSurface: Colors.black,
  onInverseSurface: Colors.white,
  inversePrimary: Colors.white,
  surfaceTint: Colors.black,
);


final ColorScheme darkMonochrome = ColorScheme(
  brightness: Brightness.dark,
  primary: Colors.white,
  onPrimary: Colors.black,
  primaryContainer: Colors.grey.shade700,
  onPrimaryContainer: Colors.white,
  secondary: Colors.white70,
  onSecondary: Colors.black,
  secondaryContainer: Colors.grey.shade600,
  onSecondaryContainer: Colors.white,
  tertiary: Colors.white54,
  onTertiary: Colors.black,
  tertiaryContainer: Colors.grey.shade500,
  onTertiaryContainer: Colors.white,
  error: Colors.white,
  onError: Colors.black,
  errorContainer: Colors.grey.shade700,
  onErrorContainer: Colors.white,
  background: Colors.black,
  onBackground: Colors.white,
  surface: Colors.black,
  onSurface: Colors.white,
  surfaceVariant: Colors.grey.shade800,
  onSurfaceVariant: Colors.white70,
  outline: Colors.grey.shade600,
  shadow: Colors.black,
  inverseSurface: Colors.white,
  onInverseSurface: Colors.black,
  inversePrimary: Colors.black,
  surfaceTint: Colors.white,
);
